### ISSUE TITLE
Roadmap v0.3

### ISSUE THREAD

**Issue by malkoG** [balpan-rs/balpan#37]
* [ ] Readme documentation
* [ ] Contributor/md

### Subcommand
* [ ] #31
* [ ] [Feature] `balpan grep` subcommand
* [ ] [Feature] `balpan toggle` subcommand
* [ ] [Feature] Support json output from `balpan grep` subcommand

### Language Support
* [ ] Support Scala
* [ ] Support Java
* [ ] Support Kotlin
* [ ] Support javascript
* [ ] Support Typescript
* [ ] Support C
* [ ] Support C++
